Repository FILMDOM-s/film-doms, pull requests merged in 2023-08, with the labels that each got.

#155 FILMDOMS fix 도메인 수정
  components/views/Auth/SignIn/SignIn.tsx
  next.config.js
  pages/auth/google.tsx
  services/api/utils.ts
Labels: fix

#157 FILMDOMS 정기 병합 작업
  components/views/Article/Main/Slide/Slider/data.ts
  components/views/Layout/Header/Avatar/Avatar.tsx
  pages/auth/google.tsx
  pages/auth/logout.tsx
  yarn.lock
Labels: enhancement

#158 FILMDOMS 정기 병합 작업
  components/views/Auth/SignIn/SignIn.tsx
  pages/auth/logout.tsx
  services/auth/apis.ts
  services/auth/mutations.ts
Labels: fix

#161 FILMDOMS feat: 컨텍스트 메뉴 프로필 박스, film universe align, critic content
  components/common/Modal/ProfileModal.tsx
  components/views/Article/Main/BoardContainer/BoardContainer.tsx
  components/views/Auth/Profile/hooks/useMyProfileBox.tsx
  components/views/Home/FilmUniverse/FilmUniverse.tsx
  components/views/Layout/Header/Avatar/Avatar.tsx
  components/views/Layout/Header/Avatar/ProfileBox/ProfileBox.tsx
  components/views/Layout/Header/Avatar/ProfileBox/index.ts
  components/views/Layout/Header/Avatar/hooks/useContextMenu.ts
  components/views/Layout/Header/Header.tsx
  hooks/useProfileModal.ts
  states/index.ts
Labels: refactor, fix

#162 FILMDOMS 정기 병합 작업
  components/views/Article/Main/BoardContainer/ArticleBoard/CriticBoard.tsx
  components/views/Article/Main/BoardContainer/BoardContainer.tsx
  components/views/Article/Write/EditorContainer.tsx
  components/views/Article/Write/UpdateEditorContainer.tsx
  components/views/Home/Critic/Critic.tsx
  components/views/Home/Critic/CriticList.tsx
  components/views/Home/FilmUniverse/FilmUniverse.tsx
  components/views/Home/FilmUniverse/FilmUniverseList.tsx
  components/views/Layout/Header/Avatar/Avatar.tsx
  mocks/handlers/article/data/filmUniverse.ts
  types/pages/article.d.ts
  types/pages/main.d.ts
  utils/convertStringToHtml.ts
Labels: enhancement, fix

#164 fix: editor, template
  components/common/Editor/Editor.tsx
  components/views/Article/Write/EditorContainer.tsx
  components/views/Article/Write/Template/index.ts
  components/views/Auth/SignUp/SignUpForm/SignUpForm.tsx
  pages/write/article/[category]/index.tsx
  services/article/apis.ts
  services/article/queries.ts
  services/queryKeys.ts
  states/index.ts
  types/pages/article.d.ts
Labels: enhancement, fix

#165 FILMDOMS final - 구글 로그인 오류 수정, fallback loading, handler, banner link
  components/common/Loading/FallbackLoading.tsx
  components/common/Loading/Loading.tsx
  components/views/Article/Detail/ArticleDetail.tsx
  components/views/Article/Detail/ArticleDetailContainer.tsx
  components/views/Article/Detail/Comment/CommentItem.tsx
  components/views/Article/Popular/ArticlePopularContainer.tsx
  components/views/Auth/SignUp/SignUpForm/SignUpForm.tsx
  components/views/Home/Banner/Banner.tsx
  components/views/Home/Banner/BannerContainer.tsx
  components/views/Home/Community/CommunityContainer.tsx
  components/views/Home/Critic/CriticContainer.tsx
  components/views/Home/FilmUniverse/FilmUniverseContainer.tsx
  components/views/MyPage/MyPageContainer.tsx
  components/views/MyPage/ProfileContainer.tsx
  components/views/MyPage/UserActivitySection/ArticleContainer/ArticleContainer.tsx
  components/views/MyPage/UserActivitySection/CommentContainer/CommentContainer.tsx
  components/views/MyPage/UserActivitySection/UserActivitySection.tsx
  mocks/handlers/index.ts
  mocks/handlers/myPage/data/article.ts
  mocks/handlers/myPage/data/comment.ts
  mocks/handlers/myPage/index.ts
  pages/_app.tsx
  pages/auth/google.tsx
  services/myPage/apis.ts
  types/pages/myPage.d.ts
Labels: enhancement, fix

#166 FILMDOMS 대댓글 수정 삭제, 세부 디자인 수정 사항
  components/common/Editor/Editor.tsx
  components/views/Article/Detail/Comment/ChildCommentItem.tsx
  components/views/Article/Detail/Comment/CommentContainer.tsx
  components/views/Article/Detail/Comment/CommentItem.stories.tsx
  components/views/Article/Detail/Comment/CommentItem.tsx
  components/views/Article/Main/Slide/Slider/Slider.tsx
  components/views/Article/Main/Slide/Slider/data.ts
  components/views/Article/Write/EditorContainer.tsx
  components/views/Article/Write/UpdateEditorContainer.tsx
  components/views/Auth/SignIn/SignIn.tsx
  components/views/MyPage/MyPageContainer.tsx
  components/views/MyPage/ProfileContainer.tsx
  components/views/MyPage/UserActivitySection/ArticleContainer/ArticleContainer.tsx
  components/views/MyPage/UserActivitySection/CommentContainer/CommentContainer.tsx
  components/views/MyPage/UserInfoSection/UserInfoSection.tsx
  hooks/useRouterChange.ts
  pages/_app.tsx
Labels: enhancement, fix

#167 FILMDOMS fix: 전반적인 수정사항 반영, 정기 병합
  components/views/Article/Detail/ArticleDetailContainer.tsx
  components/views/Article/Detail/Comment/ChildCommentItem.tsx
  components/views/Article/Detail/Comment/CommentContainer.tsx
  components/views/Article/Detail/Comment/CommentItem.stories.tsx
  components/views/Article/Detail/Comment/CommentItem.tsx
  services/article/queries.ts
Labels: fix

#169 FILMDOMS #168 소셜 로그인 관련 이슈들을 처리합니다
  components/common/RouterBoundary/RouterBoundary.tsx
  components/views/Auth/SignUp/SignUpForm/SignUpForm.tsx
  components/views/Home/Banner/Banner.tsx
  components/views/Layout/Header/Avatar/Avatar.tsx
  services/myPage/apis.ts
  states/index.ts
Labels: fix

#170 FILMDOMS #168 소셜로그인, 일반로그인 profile 조회를 동시에 수행합니다
  components/common/RouterBoundary/RouterBoundary.tsx
  components/views/Auth/SignIn/SignIn.tsx
  components/views/Auth/SignUp/SignUpForm/SignUpForm.tsx
  components/views/Home/Banner/Banner.tsx
  components/views/Layout/Header/Avatar/Avatar.tsx
  components/views/MyPage/MyPageContainer.tsx
  pages/auth/logout.tsx
  services/myPage/apis.ts
  services/myPage/queries.ts
  services/queryKeys.ts
  states/index.ts
Labels: fix

#173 FILMDOMS #169 소셜 로그인 오류 수정
  components/common/RouterBoundary/RouterBoundary.tsx
  components/views/Auth/SignIn/SignIn.tsx
  components/views/Auth/SignUp/SignUpForm/SignUpForm.tsx
  components/views/Layout/Header/Avatar/Avatar.tsx
  components/views/MyPage/MyPageContainer.tsx
  pages/auth/logout.tsx
  services/myPage/apis.ts
  services/myPage/queries.ts
  services/queryKeys.ts
Labels: enhancement, fix

#174 hotfix: 변경되지 않은 파일을 변경합니다
  components/common/RouterBoundary/RouterBoundary.tsx
  components/views/Auth/SignIn/SignIn.tsx
  components/views/Auth/SignUp/SignUpForm/SignUpForm.tsx
  components/views/Home/Banner/Banner.tsx
  components/views/Layout/Header/Avatar/Avatar.tsx
  pages/auth/logout.tsx
  states/index.ts
Labels: bug, fix

#175 FILMDOMS 최종 빌드 테스트, 에러 수정
  components/common/RouterBoundary/RouterBoundary.tsx
  components/views/Auth/SignIn/SignIn.tsx
  components/views/Auth/SignUp/SignUpForm/SignUpForm.tsx
  components/views/Home/Banner/Banner.tsx
  components/views/Layout/Header/Avatar/Avatar.tsx
  pages/auth/logout.tsx
  states/index.ts
Labels: fix

#176 hotfix: 유저 프로필 조회 쿼리를 수정하고 사용하지 않는 쿼리를 제거합니다
  components/views/MyPage/MyPageContainer.tsx
  services/myPage/apis.ts
Labels: bug, fix

#177 FILMDOMES #168 소셜 로그인 관련 이슈들을 처리합니다
  components/views/MyPage/MyPageContainer.tsx
  services/myPage/apis.ts
Labels: fix

#179 FILMDOMS #178 구글, 네이버 메타 태그를 추가합니다
  pages/_document.tsx
Labels: enhancement
