Repository FILMDOM-s/film-doms, pull requests merged in 2023-05, with the labels that each got.

#94 FILMDOMS #89 Critic 스케치
  components/views/Article/Banner/Banner.tsx
  components/views/Article/Banner/index.ts
  components/views/Article/Main/ArticleContainer.tsx
  components/views/Article/Main/BoardContainer/ArticleBoard/CriticBoard.tsx
  components/views/Article/Main/BoardContainer/ArticleBoard/index.ts
  components/views/Article/Main/BoardContainer/BoardContainer.tsx
  components/views/Article/Slide/Controller/Controller.tsx
  components/views/Article/Slide/Controller/index.ts
  components/views/Article/Slide/SlideContainer.tsx
  components/views/Article/Slide/Slider/Slider.tsx
  components/views/Article/Slide/Slider/index.ts
  components/views/Article/Slide/index.ts
  components/views/Article/index.ts
  components/views/Home/Banner/Slider/SliderWrapper/SliderWrapper.stories.tsx
  components/views/Layout/ArticleLayout/ArticleLayout.tsx
  components/views/Layout/Header/Header.tsx
  constants/article.ts
  pages/article/[category]/index.tsx
  pages/critic/[id]/index.tsx
  pages/critic/index.tsx
Labels: documentation, enhancement, good first issue, question, refactor, suggest, style

#95 FILMDOMS #90 로그인, 회원가입
  assets/svgs/common/Instagram.tsx
  components/common/FormError/FormError.tsx
  components/common/FormError/index.ts
  components/views/_App/Auth/index.ts
  components/views/_App/Auth/withAuth.tsx
  hooks/useLazyQuery.ts
  package.json
  pages/auth/signin.tsx
  pages/auth/signout.tsx
  pages/auth/signup.tsx
  yarn.lock
Labels: documentation, enhancement, good first issue, help wanted, question, refactor, style

#96 feat: merge conflict resolve
  assets/svgs/common/SlideNext.tsx
  assets/svgs/common/SlidePrev.tsx
  components/common/Modal/Modal.tsx
  components/common/Modal/index.ts
  components/views/About/AboutContainer.tsx
  components/views/About/Section/CommonSection/CommonSection.tsx
  components/views/About/constants.tsx
  components/views/Article/Main/CriticContainer.tsx
  components/views/Article/Main/Slide/SlideContainer.tsx
  components/views/Article/Main/Slide/Slider/Slider.tsx
  components/views/Article/Main/Slide/Slider/data.ts
  components/views/Article/Main/Slide/Slider/index.ts
  components/views/Article/Main/Slide/index.ts
  components/views/Article/Main/index.ts
  components/views/Auth/SignIn/SignIn.tsx
  components/views/Auth/SignIn/index.ts
  components/views/Auth/index.ts
  components/views/Home/Banner/BannerContainer.tsx
  components/views/Home/Banner/Slider/SliderWrapper/SliderWrapper.tsx
  components/views/Home/Community/CommunityContainer.tsx
  components/views/Layout/AppLayout/AppLayout.tsx
  constants/auth/regex.ts
  constants/auth/terms.ts
  hooks/useModal.ts
  pages/_app.tsx
  pages/article/[category]/[id]/index.tsx
  pages/notice/[id]/index.tsx
  pages/notice/index.tsx
  states/index.ts
  styles/modal.css
Labels: fix

#101 FILMDOMS #100 마이페이지 디자인 변경사항을 수정합니다
  components/views/MyPage/InterestMovieSection/InterestMovieSection.tsx
  components/views/MyPage/UserInfoSection/UserInfoSection.tsx
  components/views/MyPage/constants.ts
Labels: fix, style

#106 FILMDOMS #105 next-auth, next-theme 제거
  package.json
  pages/api/auth/[...nextauth].ts
  pages/api/get-posts.ts
  yarn.lock
Labels: fix

#107 FILMDOMS #105 FIX recoil 오류
  package.json
  pages/api/auth/[...nextauth].ts
  pages/api/get-posts.ts
  yarn.lock
Labels: fix

#111 FILMDOMS #108 SignUp 페이지를 리팩토링합니다
  components/views/Auth/SignUp/SignUpContainer.tsx
  components/views/Auth/SignUp/index.ts
  constants/auth/regex.ts
  pages/auth/signup.tsx
  services/auth/apis.ts
  services/auth/index.ts
  services/auth/mutations.ts
  types/auth.d.ts
Labels: refactor

#115 FILMDOMS #102 회원가입 페이지를 변경된 디자인에 맞게 구성합니다
  components/views/Auth/SignUp/Header/Header.tsx
  components/views/Auth/SignUp/Header/index.ts
  components/views/Auth/SignUp/SignUpContainer.tsx
  components/views/Auth/SignUp/SignUpForm/SignUpForm.tsx
  components/views/Auth/SignUp/SignUpForm/index.ts
Labels: enhancement, fix, style

#116 FILMDOMS #105 로그인 디자인 변경 사항 반영
  components/common/Modal/Modal.tsx
  components/views/Auth/SignIn/SignIn.tsx
  pages/auth/signin.tsx
Labels: style

#119 FILMDOMS main <- develop merge
  components/common/Modal/Modal.tsx
  components/views/Auth/SignIn/SignIn.tsx
  components/views/Auth/SignUp/Header/Header.tsx
  components/views/Auth/SignUp/Header/index.ts
  components/views/Auth/SignUp/SignUpContainer.tsx
  components/views/Auth/SignUp/SignUpForm/SignUpForm.tsx
  components/views/Auth/SignUp/SignUpForm/index.ts
  components/views/Auth/SignUp/SignUpForm/style.ts
  components/views/Auth/SignUp/index.ts
  constants/auth/regex.ts
  pages/auth/signin.tsx
  pages/auth/signup.tsx
  services/auth/apis.ts
  services/auth/index.ts
  services/auth/mutations.ts
  types/auth.d.ts
Labels: enhancement

#120 FILMDOMS #112 SignUp 기능을 구현합니다
  components/views/Auth/SignUp/SignUpForm/SignUpForm.tsx
  components/views/Auth/SignUp/SignUpForm/constants.ts
  components/views/Auth/SignUp/SignUpForm/utils.ts
  constants/auth/regex.ts
  services/api/index.ts
  services/auth/apis.ts
  services/auth/mutations.ts
  types/auth.d.ts
Labels: enhancement

#121 FILMDOMS #90 비밀번호 변경, 게시물 작성(60%), 로그인 기능 구현
  components/common/Editor/Editor.tsx
  components/common/Editor/index.ts
  components/views/Article/Main/SearchForm/constants.ts
  components/views/Article/Write/Check/LabeledCheckbox.tsx
  components/views/Article/Write/Check/index.ts
  components/views/Article/Write/EditorContainer.tsx
  components/views/Article/Write/File/File.tsx
  components/views/Article/Write/File/index.ts
  components/views/Article/Write/index.ts
  components/views/Auth/Help/Email/Email.tsx
  components/views/Auth/Help/Email/index.ts
  components/views/Auth/Help/Header/Header.tsx
  components/views/Auth/Help/Header/index.ts
  components/views/Auth/Help/Help.tsx
  components/views/Auth/Help/Password/Password.tsx
  components/views/Auth/Help/Password/index.ts
  components/views/Auth/Help/index.ts
  components/views/Auth/SignIn/SignIn.tsx
  components/views/Auth/index.ts
  package.json
  pages/auth/help.tsx
  pages/write/article/[category]/index.tsx
  services/article/apis.ts
  services/article/index.ts
  services/article/mutations.ts
  services/auth/apis.ts
  services/auth/mutations.ts
  types/auth.d.ts
  types/pages/article.d.ts
  yarn.lock
Labels: enhancement

#122 FILMDOMS #90 에디터 뷰 기능 구현
  components/common/Select/CategorySelect/CategorySelect.stories.tsx
  components/common/Select/CategorySelect/CategorySelect.tsx
  components/common/Select/CategorySelect/index.ts
  components/common/Select/index.ts
  components/views/Article/Main/BoardContainer/ArticleBoard/CriticBoard.tsx
  components/views/Article/Main/SearchForm/constants.ts
  components/views/Article/Write/Check/LabeledCheckbox.tsx
  components/views/Article/Write/EditorContainer.tsx
  components/views/Article/Write/File/File.tsx
  components/views/Auth/Help/Help.tsx
  components/views/Auth/Help/Password/Password.tsx
  components/views/Auth/SignIn/SignIn.tsx
  components/views/Auth/SignUp/SignUpForm/SignUpForm.tsx
  mocks/handlers/article/data/filmUniverse.ts
  pages/critic/[id]/index.tsx
  pages/critic/index.tsx
  types/pages/article.d.ts
Labels: enhancement

#123 FILMDOMS #112 회원가입 페이지의 기능을 구현합니다
  components/views/Auth/SignUp/SignUpForm/SignUpForm.tsx
  services/api/index.ts
  services/api/utils.ts
  services/auth/apis.ts
  services/auth/mutations.ts
Labels: enhancement
