Repository FILMDOM-s/film-doms, pull requests merged in 2023-04, with the labels that each got.

#64 FILMDOMS #63 날짜 형식 변경
  components/views/Home/Notice/Notice.tsx
  mocks/handlers/notice/index.ts
Labels: refactor

#65 브랜치 동기화
  README.md
  components/views/Home/Notice/Notice.tsx
  mocks/handlers/notice/index.ts
  services/api/index.ts
Labels: fix

#75 FILMDOMS #69 [인기 게시글 구현] coded by 시형
  components/views/Article/Main/ArticlePage.stories.tsx
  components/views/Article/Popular/ArticlePopular.tsx
  components/views/Article/Popular/ArticlePopularContainer.stories.tsx
  components/views/Article/Popular/ArticlePopularContainer.tsx
  mocks/handlers/index.ts
  mocks/handlers/popular/data/index.ts
  mocks/handlers/popular/index.ts
  pages/article/[category]/[id]/index.tsx
  pages/article/[category]/index.tsx
  services/popular/apis.ts
  services/popular/index.ts
  services/popular/queries.ts
  services/queryKeys.ts
Labels: documentation, enhancement, refactor, style

#76 FILMDOMS #merge 정기 병합 작업
  components/views/Article/Main/ArticlePage.stories.tsx
  components/views/Article/Popular/ArticlePopular.tsx
  components/views/Article/Popular/ArticlePopularContainer.stories.tsx
  components/views/Article/Popular/ArticlePopularContainer.tsx
  mocks/handlers/index.ts
  mocks/handlers/popular/data/index.ts
  mocks/handlers/popular/index.ts
  pages/article/[category]/[id]/index.tsx
  pages/article/[category]/index.tsx
  services/popular/apis.ts
  services/popular/index.ts
  services/popular/queries.ts
  services/queryKeys.ts
Labels: enhancement

#78 style: critic 섹션 상단 여백 추가
  components/views/Home/Critic/CriticContainer.tsx
Labels: style

#81 FILMDOMS #80 메인 페이지 CLS 이슈를 해결합니다
  components/common/Loading/Loading.tsx
  components/views/Home/Banner/BannerContainer.tsx
  components/views/Home/Banner/Slider/SliderWrapper/SliderWrapper.tsx
  components/views/Home/Community/CommunityContainer.tsx
  components/views/Home/Critic/CriticContainer.tsx
  components/views/Home/Notice/NoticeContainer.tsx
  services/banner/queries.ts
Labels: refactor, fix, suggest

#83 fix: husky가 정상동작하도록 합니다
  .eslintrc.json
  .husky/pre-commit
  components/views/Article/Detail/ArticleDetail.tsx
  components/views/Article/Detail/Comment/ChildCommentItem.tsx
  components/views/Article/Detail/Comment/CommentContainer.tsx
  components/views/Article/Detail/Comment/CommentItem.stories.tsx
  components/views/Article/Detail/Comment/CommentItem.tsx
  components/views/Article/Detail/ProfileBar/ProfileBar.stories.tsx
  components/views/Article/Detail/ProfileBar/ProfileBar.tsx
  components/views/Article/Main/ArticlePage.stories.tsx
  components/views/Article/Popular/ArticlePopular.tsx
  components/views/Article/Popular/ArticlePopularContainer.stories.tsx
  components/views/Article/Popular/ArticlePopularContainer.tsx
  components/views/Home/Banner/Slider/SliderWrapper/SliderWrapper.tsx
  components/views/Home/Critic/Critic.stories.tsx
  components/views/Home/Nav/NavContainer.tsx
  components/views/Home/Notice/Notices.tsx
  components/views/Layout/Header/Header.tsx
  components/views/Layout/SideNav/SideNav.tsx
  mocks/handlers/popular/data/index.ts
  mocks/handlers/popular/index.ts
  package.json
  pages/about/index.tsx
  pages/article/[category]/[id]/index.tsx
  services/notice/queries.ts
  services/popular/apis.ts
  services/popular/index.ts
  services/popular/queries.ts
  yarn.lock
Labels: bug, fix

#84 FILMDOMS #79 About 페이지 퍼블리싱
  assets/svgs/alphabet/F.tsx
  assets/svgs/alphabet/I.tsx
  assets/svgs/alphabet/L.tsx
  assets/svgs/alphabet/M.tsx
  assets/svgs/alphabet/index.ts
  assets/svgs/common/FilmDomsAnime.tsx
  components/views/About/AboutContainer.tsx
  components/views/About/Section/CommonSection/CommonSection.tsx
  components/views/About/Section/CommonSection/index.ts
  components/views/About/Section/TopSection/TopSection.tsx
  components/views/About/Section/TopSection/hooks.ts
  components/views/About/Section/TopSection/index.ts
  components/views/About/Section/index.ts
  components/views/About/constants.tsx
  components/views/About/index.ts
  components/views/Home/Banner/Slider/SliderWrapper/SliderWrapper.tsx
  components/views/Layout/AppLayout/AppLayout.tsx
  components/views/Layout/Header/Header.tsx
  package.json
  pages/_app.tsx
  pages/about/index.tsx
  styles/anime.css
  styles/carousel.css
  styles/globals.css
  yarn.lock
Labels: documentation, enhancement, help wanted, refactor, suggest, style

#93 FILMDOMS #92 댓글 DTO를 변경된 서버 api 명세에 맞춥니다
  components/views/Article/Detail/Comment/CommentItem.stories.tsx
  components/views/Article/Detail/Comment/CommentItem.tsx
  services/article/apis.ts
  types/pages/article.d.ts
Labels: fix
