Repository FILMDOM-s/film-doms, pull requests merged in 2023-02, with the labels that each got.

#17 FILMDOMS #[11,12] 메인 페이지 메인 슬라이더와 Notice 슬라이더를 구현합니다.
  .prettierrc
  components/Header.tsx
  components/MainSwiper.tsx
  components/NoticeSwiper.tsx
  components/SideNav.tsx
  pages/_app.tsx
  pages/index.tsx
  public/assets/film-dummy.jpg
  styles/carousel.css
  styles/globals.css
  styles/side-nav.css
Labels: enhancement

#20 FILMDOMS #18 메인페이지의 Critic 섹션 구현
  components/views/Home/Critic/Critic.tsx
  components/views/Home/Critic/CriticConatiner.tsx
  components/views/Home/Critic/Critics.tsx
  components/views/Home/Critic/index.ts
  components/views/Home/HomeContainer.tsx
  next.config.js
  services/critic/apis.ts
  services/critic/index.ts
  services/critic/queries.ts
Labels: enhancement

#28 FILMDOMS: #26 OpenGraph 컴포넌트를 구현합니다
  components/common/OpenGraph/OpenGraph.tsx
  components/common/OpenGraph/index.ts
  components/common/index.ts
Labels: enhancement

#25 FILMDOMS #24 community 섹션 스타일을 수정합니다
  components/common/Section/SectionTitle.tsx
  components/views/Home/Community/CommunityContainer.tsx
  components/views/Home/Community/MovieReview/MovieReview.tsx
  components/views/Home/Community/MovieReview/MovieReviewContainer.tsx
  components/views/Home/Community/Recent/Recent.tsx
  components/views/Home/Community/Recent/RecentContainer.tsx
  components/views/Home/HomeContainer.tsx
Labels: fix

#29 FILMDOMS #27 _app을 리팩토링합니다
  components/views/_App/Script/AppScript.tsx
  components/views/_App/Script/Gtag/Gtag.tsx
  components/views/_App/Script/Gtag/index.ts
  components/views/_App/Script/NaverPay/NaverPay.tsx
  components/views/_App/Script/NaverPay/index.ts
  components/views/_App/Script/index.ts
  components/views/_App/hooks/index.ts
  components/views/_App/hooks/useStartWorker.ts
  components/views/_App/index.ts
  hooks/index.ts
  hooks/useRouterChange.ts
  next.config.js
  package.json
  pages/_app.tsx
  yarn.lock
Labels: refactor, fix
