Repository FILMDOM-s/film-doms, pull requests merged in 2023-03, with the labels that each got.

#33 FILMDOMS: #30 msw의 warning을 해결합니다
  .github/pull_request_template.md
  .prettierrc
  components/views/Home/Banner/Slider/SliderWrapper/index.ts
  components/views/Home/Nav/Nav.tsx
  components/views/Home/Nav/NavContainer.tsx
  components/views/Home/Nav/index.ts
  components/views/Home/Notice/Notice.tsx
  components/views/Home/Notice/NoticeContainer.tsx
  components/views/Home/Notice/Notices.tsx
  components/views/Layout/Header/Header.tsx
  constants/constants.ts
  hooks/useResizeWindow.ts
  mocks/index.ts
  pages/_app.tsx
  services/api/index.ts
  styles/carousel.css
  styles/emotion/mediaQuery/index.ts
  styles/globals.css
  styles/side-nav.css
Labels: fix

#36 FILMDOMS #31 production에서의 이미지 최적화를 위한 sharp 패키지 추가 및 VoidFuncion 리팩토링
  components/views/Layout/Header/Header.tsx
  components/views/Layout/SideNav/SideNav.tsx
  package.json
  yarn.lock
Labels: refactor

#37 Storybook playground
  .eslintrc.json
  .gitignore
  .storybook/main.js
  .storybook/preview.jsx
  components/common/Badge/Badge.stories.tsx
  components/common/Badge/Badge.tsx
  components/views/Home/Banner/BannerContainer.stories.tsx
  components/views/Home/Banner/Slider/SliderWrapper/SliderWrapper.stories.tsx
  components/views/Home/Community/CommunityContainer.stories.tsx
  components/views/Home/Community/MovieReview/MovieReview.stories.tsx
  components/views/Home/Community/MovieReview/MovieReviewContainer.stories.tsx
  components/views/Home/Community/Recent/Recent.stories.tsx
  components/views/Home/Community/Recent/RecentContainer.stories.tsx
  components/views/Home/Critic/Critic.stories.tsx
  components/views/Home/Critic/CriticContainer.stories.tsx
  components/views/Home/Critic/Critics.stories.tsx
  components/views/Home/HomeContainer.stories.tsx
  components/views/Home/Nav/Nav.stories.tsx
  components/views/Home/Nav/NavContainer.stories.tsx
  components/views/Home/Notice/Notice.stories.tsx
  components/views/Home/Notice/NoticeContainer.stories.tsx
  components/views/Home/Notice/Notices.stories.tsx
  components/views/Layout/AppLayout/AppLayout.stories.tsx
  components/views/Layout/Footer/Footer.stories.tsx
  components/views/Layout/Header/Header.stories.tsx
  components/views/Layout/SideNav/SideNav.stories.tsx
  components/views/Layout/SideNav/SideNavList.stories.tsx
  components/views/Layout/SideNav/SideNavListItem.stories.tsx
  package.json
  services/api/index.ts
  styles/emotion/mediaQuery/index.ts
  styles/emotion/utils.ts
  tsconfig.json
  utils/getMockImage.ts
  utils/index.ts
  yarn.lock
Labels: enhancement, good first issue, help wanted, refactor, suggest

#46 FILMDOMS #39 스타일 가이드를 적용합니다
  .github/workflows/chromatic.yml
  .storybook/main.js
  .storybook/preview.jsx
  assets/svgs/Icons.stories.tsx
  assets/svgs/common/ArrowRight.tsx
  assets/svgs/common/Instagram.tsx
  assets/svgs/common/Person.tsx
  assets/svgs/common/Search.tsx
  assets/svgs/common/index.ts
  components/common/Button/Common/Common.stories.tsx
  components/common/Button/Common/Common.tsx
  components/common/Button/Common/index.ts
  components/common/Button/Ticket/Ticket.stories.tsx
  components/common/Button/Ticket/Ticket.tsx
  components/common/Button/Ticket/index.ts
  components/common/Button/index.ts
  components/common/Button/type/index.ts
  components/common/Tag/Shape/Round/Round.stories.tsx
  components/common/Tag/Shape/Round/Round.tsx
  components/common/Tag/Shape/Round/index.ts
  components/common/Tag/Shape/Square/Square.stories.tsx
  components/common/Tag/Shape/Square/Square.tsx
  components/common/Tag/Shape/Square/index.ts
  components/common/Tag/Shape/index.ts
  components/common/Tag/Tag.tsx
  components/common/Tag/index.ts
  components/common/Tag/type/index.ts
  components/common/index.ts
  styles/emotion/color/colors.stories.tsx
  styles/emotion/color/index.ts
  styles/emotion/index.ts
  styles/emotion/typography/index.ts
  styles/emotion/typography/typography.stories.tsx
Labels: enhancement, fix, style

#48 FILMDOMS #38 #39 button의 icon을 props로 받도록 수정합니다
  components/common/Button/Common/Common.stories.tsx
  components/common/Button/Common/Common.tsx
  components/common/Button/Ticket/Ticket.stories.tsx
  components/common/Button/Ticket/Ticket.tsx
  components/common/Button/type/index.ts
  components/common/Tag/Shape/Round/Round.stories.tsx
  components/common/Tag/Shape/Square/Square.stories.tsx
Labels: refactor, fix

#49 FILMDOMS #42 [리뉴얼] Community Section
  .storybook/preview.jsx
  components/common/Error/Error.tsx
  components/common/Error/index.ts
  components/common/Loading/Loading.tsx
  components/common/Loading/index.ts
  components/common/RenderIf/RenderIf.tsx
  components/common/RenderIf/index.ts
  components/common/Section/SectionContainer.tsx
  components/common/Section/SectionHeader.tsx
  components/common/index.ts
  components/views/Home/Community/CommunityContainer.stories.tsx
  components/views/Home/Community/CommunityContainer.tsx
  components/views/Home/Community/MovieReview/MovieReview.stories.tsx
  components/views/Home/Community/MovieReview/MovieReview.tsx
  components/views/Home/Community/MovieReview/MovieReviewContainer.tsx
  components/views/Home/Community/Recent/Recent.stories.tsx
  components/views/Home/Community/Recent/Recent.tsx
  components/views/Home/Community/Recent/RecentContainer.tsx
  components/views/Home/HomeContainer.tsx
  mocks/handlers/recent/index.ts
  mocks/handlers/review/index.ts
  pages/_app.tsx
  styles/emotion/mediaQuery/index.ts
  styles/emotion/utils.ts
  types/utils.d.ts
Labels: enhancement, refactor, fix, style

#50 FILMDOMS #41 변경된 footer를 구현합니다
  assets/images/common/index.ts
  assets/images/common/logo_eng_ver_gray8.png
  components/common/Divider/Divider.stories.tsx
  components/common/Divider/Divider.tsx
  components/common/Divider/index.ts
  components/common/index.ts
  components/views/Layout/Footer/Footer.tsx
  components/views/Layout/Footer/LinkSection.tsx
  components/views/Layout/Footer/constants.ts
  components/views/Layout/Footer/type.ts
Labels: enhancement, fix, style

#52 FILMDOMS #40 디자인 시안 변경에 따른 헤더 작업
  assets/svgs/common/LogoWhite.tsx
  assets/svgs/common/index.ts
  components/views/Home/HomeContainer.tsx
  components/views/Home/Nav/Nav.tsx
  components/views/Home/Nav/NavContainer.tsx
  components/views/Layout/Header/Header.tsx
Labels: documentation, enhancement, question, refactor, suggest, style

#55 FILMDOMS #44 디자인 시안 변경에 따른 Notice Section 작업
  components/views/Home/Notice/Notice.stories.tsx
  components/views/Home/Notice/Notice.tsx
  components/views/Home/Notice/NoticeContainer.tsx
  components/views/Home/Notice/Notices.tsx
  components/views/Layout/SideNav/SideNavList.stories.tsx
  components/views/Layout/SideNav/SideNavListItem.stories.tsx
  mocks/handlers/notice/index.ts
  types/notice..d.ts
Labels: documentation, enhancement, question, refactor, suggest, style

#60 FILMDOMS #56 스토리북 디자인 불일치 수정
  components/views/Home/Banner/BannerContainer.stories.tsx
  components/views/Home/Banner/Slider/SliderWrapper/SliderWrapper.stories.tsx
Labels: refactor

#61 FILMDOMS #59 Largest Contentful Paint element에 대한 우선 로딩 적용
  components/views/Home/Banner/Slider/SliderWrapper/SliderWrapper.tsx
Labels: refactor
