Repository FILMDOM-s/film-doms, pull requests merged in 2023-06, with the labels that each got.

#124 FILMDOMS #102 회원가입 페이지의 디자인을 수정합니다
  components/views/Auth/SignUp/SignUpForm/SignUpForm.tsx
Labels: fix, style

#126 FILMDOMS #125 이미지 업로드, 아티클 생성, 댓글 생성
  components/common/Editor/Editor.tsx
  components/common/Editor/ReadOnlyEditor.tsx
  components/common/Editor/index.ts
  components/views/Article/Detail/ArticleDetail.tsx
  components/views/Article/Detail/Comment/CommentContainer.tsx
  components/views/Article/Detail/Comment/CommentForm.tsx
  components/views/Article/Detail/Comment/CommentItem.stories.tsx
  components/views/Article/Detail/Comment/CommentItem.tsx
  components/views/Article/Main/ArticleContainer.tsx
  components/views/Article/Write/EditorContainer.tsx
  components/views/Article/Write/Select/Select.tsx
  components/views/Article/Write/Select/index.ts
  components/views/Auth/SignIn/SignIn.tsx
  services/article/apis.ts
  services/article/mutations.ts
  services/file/apis.ts
  services/file/index.ts
  services/file/mutations.ts
  types/file.d.ts
  types/pages/article.d.ts
Labels: enhancement

#128 FILMDOMS #127 메인, 어바웃 페이지의 UI를 수정합니다
  assets/images/banner/filmdoms_banner_image 1.png
  assets/images/banner/index.ts
  components/views/About/Section/CommonSection/CommonSection.tsx
  components/views/About/constants.tsx
  components/views/Home/Banner/Banner.tsx
  types/pages/main.d.ts
Labels: fix

#130 FILMDOMS #129 About Title을 수정합니다
  components/views/About/Section/TopSection/TopSection.tsx
Labels: fix

#131 FILMDOMS #125 Google OAUTH Login
  components/views/Auth/SignIn/SignIn.tsx
  components/views/Auth/SignUp/SignUpContainer.tsx
  components/views/Auth/SignUp/SignUpForm/SignUpForm.tsx
  next.config.js
  pages/auth/google.tsx
  services/auth/apis.ts
  services/auth/mutations.ts
  services/auth/queries.ts
  types/auth.d.ts
Labels: enhancement, refactor

#133 FILMDOMS #88 마이페이지를 기능을 구현합니다
  .vscode/settings.json
  components/views/Layout/Header/Avatar/Avatar.tsx
  components/views/Layout/Header/Avatar/index.ts
  components/views/Layout/Header/Header.tsx
  components/views/MyPage/MyPageContainer.tsx
  components/views/MyPage/ProfileSection/ProfileSection.tsx
  components/views/MyPage/UserInfoSection/UserInfoSection.tsx
  mocks/handlers/myPage/data/index.ts
  mocks/handlers/myPage/data/user.ts
  mocks/handlers/myPage/index.ts
  services/file/apis.ts
  services/myPage/apis.ts
  services/myPage/index.ts
  services/myPage/mutations.ts
  types/auth.d.ts
  types/pages/myPage.d.ts
Labels: enhancement

#136 FILMDOMS #132 Tag를 영어로 변경합니다
  components/views/Article/Main/TagList/TagList.tsx
Labels: fix

#137 FILMDOMS #134 Critic 상세 게시글 하단 UI 이슈를 해결합니다
  components/views/Article/Main/BoardContainer/ArticleBoard/CriticBoard.tsx
Labels: bug

#138 FILMDOMS #135 메인페이지 연결 링크를 최신화합니다
  components/views/Home/Community/Recent/Recent.tsx
  components/views/Home/Critic/CriticContainer.tsx
  components/views/Home/FilmUniverse/FilmUniverseContainer.tsx
Labels: bug, fix

#141 FILMDOMS #140 비로그인 시, 헤더 유저 아이콘 렌더링 이슈를 해결합니다
  components/views/Layout/Header/Avatar/Avatar.tsx
  components/views/Layout/Header/Header.tsx
  pages/_app.tsx
Labels: bug
